<?php return array (
  'site_web_title' => '小丑路人博客',
  'site_web_author' => '小丑路人',
  'site_web_keywords' => '小丑路人,小丑,路人,小丑疯狂吧,小丑博客,博客,laravel,yii,mysql',
  'site_web_description' => '小丑路人,小丑,路人,小丑疯狂吧,小丑博客,博客,laravel,yii,mysql',
  'site_web_site_icp' => '晋ICP备18007574号-1',
  'site_web_logo' => '/static/blog.jpg',
  'START_API_LOGS' => '1',
  'ARTICLE_CACHE_TIME' => '60',
  'WEB_SITE_CLOSE' => '0',
  'config_group_list' => 
  array (
    0 => '不分组',
    1 => '基本',
    2 => '内容',
    3 => '用户',
    4 => '系统',
    5 => '博主',
    6 => '开发者',
    7 => '网站后台',
    8 => 'JWT',
    9 => '小丑社区配置',
    10 => '数据库',
    11 => '邮件',
    12 => 'SMS',
    13 => 'QQ登录',
    14 => '微信登录',
    15 => 'Github登录',
    16 => '新浪登录',
  ),
  'config_type_list' => 
  array (
    0 => '字符串',
    1 => '文本',
    2 => '数字',
    3 => '数组',
    4 => '枚举',
    5 => '图片',
  ),
  'web_detault_show_img' => '/assets/blog.jpg',
  'site_web_qq' => '2278757482',
  'site_web_wx' => 'ren2278757482',
  'site_web_email' => '2278757482@qq.com',
  'API_PREFIX' => '',
  'API_ADMIN_PREFIX' => 'admin',
  'WEB_API_NAMESPACE' => '\\Web',
  'API_BLOG_NAMESPACE' => '\\Admin\\Blog',
  'API_SYSTEM_NAMESPACE' => '\\Admin\\System',
  'API_ADMIN_NAMESPACE' => '\\Admin\\BasicAdmin',
  'API_LOG_NAMESPACE' => '\\Admin\\Logs',
  'WEB_AUTHOR_INDUSTRY' => 'PHP',
  'web_admin_title' => '小丑路人博客后台管理',
  'WEB_ADMIN_KEYWORDS' => '小丑路人博客后台',
  'WEB_ADMIN_DESCRIPTION' => '小丑路人博客后台',
  'MENU_TYPE_LIST' => 
  array (
    0 => '作为频道页，不可作为栏目发布文章',
    1 => '不直接发布内容，用于跳转页面',
    2 => '作为发布栏目，文章列表模式',
    3 => '单页面模式，例如企业简介',
  ),
  'ADMIN_PREFIX' => 'cnpscy_blog_admin',
  'ADMIN_NAMESPACE' => 'Web\\BasicAdmin',
  'ADMIN_VIEWS' => '/_admin/',
  'privateKey' => '&lt;&lt;&lt;EOD-----BEGIN RSA PRIVATE KEY-----MIICXAIBAAKBgQC8kGa1pSjbSYZVebtTRBLxBz5H4i2p/llLCrEeQhta5kaQu/RnvuER4W8oDH3+3iuIYW4VQAzyqFpwuzjkDI+17t5t0tyazyZ8JXw+KgXTxldMPEL95+qVhgXvwtihXC1c5oGbRlEDvDF6Sa53rcFVsYJ4ehde/zUxo6UvS7UrBQIDAQABAoGAb/MXV46XxCFRx',
  'publicKey' => '&lt;&lt;&lt;EOD-----BEGIN PUBLIC KEY-----MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC8kGa1pSjbSYZVebtTRBLxBz5H4i2p/llLCrEeQhta5kaQu/RnvuER4W8oDH3+3iuIYW4VQAzyqFpwuzjkDI+17t5t0tyazyZ8JXw+KgXTxldMPEL95+qVhgXvwtihXC1c5oGbRlEDvDF6Sa53rcFVsYJ4ehde/zUxo6UvS7UrBQIDAQ',
  'jwt_leeway' => '60',
  'jwt_token_name' => 'cnpscy-token',
  'return_jwt_token_name' => 'jwt_token',
  'server_user_unqiue' => 'login-user-id',
  'start_api_logs' => '1',
  'start_admin_operation_logs' => '1',
  'admin_prefix_url' => 'admin1',
  'resource_version_number' => '2019527',
  'admin_default_pass' => '123456',
  'web_cdn_address' => '',
  'cnpscy_version_number' => 'v1.0',
  'system_timezone' => 'Asia/Shanghai',
  'forbiddenip' => '127.0.0.1',
  'languages' => '',
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '',
  'mail_smtp_pass' => '',
  'mail_verify_type' => '0',
  'mail_from_email' => '2278757482@qq.com',
  'admin_login_view' => '0',
  'admin_info_session_unique' => 'admin_info',
  'admin_rabc_session_unique' => 'admin_rabc',
  'order_status_list' => 
  array (
    0 => '尚未付款',
    1 => '已取消',
    2 => '已付款-待发货',
    3 => '已发货-待收货',
    4 => '已确定收货-待评论',
    5 => '已完成',
    6 => '订单异常',
    7 => '退货',
  ),
  'admin_menu_session_unique' => 'rabc_menus_list',
);