<?php

namespace app\admin\controller;

use think\validate\ValidateRule;

class Admins extends Common
{
    public function initialize()
    {
        $this->model = model('./Rabc/Admins');
        $this->requestValidator = 'AdminValidate';
        parent::initialize();
    }

    public function delete()
    {
        if (intval(input($this->model->pk, 0)) == 1) return self::apiAdminReturn(['msg' => '禁止删除操作！']);
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}