<?php

namespace app\admin\controller;

use app\service\ConfigService;

class Configs extends Common
{
    public function initialize()
    {
        $this->model = model('Configs');
        parent::initialize();
    }

    public function index($extends_info = [])
    {
        $this->assign('configs_list', ConfigService::getAdminGroupList());
        $this->assign('config_group_list', cnpscy_config('config_group_list'));
        return parent::index();
    }

    public function detail()
    {
        if (request()->isPost()){
            $data = $this->model->getDetail(input($this->model->pk, 0));
            $data['config_type_list'] = cnpscy_config('config_type_list');
            $data['config_group_list'] = cnpscy_config('config_group_list');
            return self::apiAdminReturn([
                'data' => $data,
            ]);
        }
        $this->assign('config_group_list', cnpscy_config('config_group_list'));
        $this->assign('config_type_list', cnpscy_config('config_type_list'));
        return parent::detail(); // TODO: Change the autogenerated stub
    }

    public function pushRefreshConfig()
    {
        \app\common\model\Configs::pushRefreshConfig();
        return parent::apiAdminReturn(['status' => 1, 'msg' => lang('_SYNCHRONOUS_SUCCESS_')]);
    }
}