<?php

namespace app\admin\controller;

class Roles extends Common
{
    public function initialize()
    {
        $this->model = model('./Rabc/Roles');
        $this->requestValidator = 'RoleValidate';
        parent::initialize();
    }

    public function getSelectLists()
    {
        return json([
            'data' => $this->model->where([
                    'is_check' => 1,
                    'is_delete' => 0,
                ])->select(),
            'status' => 1,
        ]);
    }

    public function delete()
    {
        if (intval(input($this->model->pk, 0)) == 1) return self::apiAdminReturn(['msg' => '禁止删除操作！']);
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}